name: Build Notification

on:
  workflow_run:
    workflows: ["YourBuildWorkflowName"]  # Replace with your build workflow name
    types:
      - completed

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Notify user via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Build completed"
          body: "Your build has been completed." # This should include the ticket number of the completed build.
          to: user@example.com  # Replace with the user's email address
