# The code below is sugestion from chatgpt
# Main.yml is the workflow acting as the build job, that gets the QA notiifed after its built is complete
# she is part of a team called "Ternut QA" in github
# Her email is "maya.john@ternut.health" using gmail
# Her username in github is te-maya-john

#task: anytime a build is complete, she gets a notification with the list of ticket built e.g. ET-207 

# I want both workflow run to show in github actions.

name: Build Notification

on:
  # workflow_run:
  #   workflows: ["YourBuildWorkflowName"]  # Replace with your build workflow name
  #   types:
  #     - completed

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Notify user via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Build completed"
          body: "Your build has been completed." # This should include the ticket number of the completed build.
          to: user@example.com  # Replace with the user's email address
